package com.smile.aceeconomy.operations;

import com.smile.aceeconomy.infrastructure.persistence.json.JsonModel;
import com.smile.aceeconomy.infrastructure.persistence.json.SnapshotPreflight;
import com.smile.aceeconomy.ports.Clock;
import com.smile.aceeconomy.ports.persistence.PersistenceException;
import com.smile.aceeconomy.ports.persistence.PersistenceLifecycle;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.nio.ByteBuffer;
import java.nio.channels.FileChannel;
import java.nio.charset.StandardCharsets;
import java.nio.file.DirectoryStream;
import java.nio.file.FileAlreadyExistsException;
import java.nio.file.Files;
import java.nio.file.LinkOption;
import java.nio.file.NoSuchFileException;
import java.nio.file.Path;
import java.nio.file.SecureDirectoryStream;
import java.nio.file.StandardOpenOption;
import java.nio.file.attribute.BasicFileAttributeView;
import java.nio.file.attribute.BasicFileAttributes;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.EnumSet;
import java.util.HexFormat;
import java.util.Locale;
import java.util.Set;
import java.util.concurrent.locks.ReentrantLock;
import java.util.function.Supplier;
import java.util.regex.Pattern;

/**
 * Managed, safety-gated backup / restore application service over the existing
 * {@link PersistenceLifecycle} contract.
 *
 * <p>Behavior contract (see docs/persistence.md and docs/operations.md):</p>
 * <ul>
 *   <li>Snapshots are written only under the plugin-controlled {@code <dataFolder>/backups}
 *       directory with handle-relative, never-overwriting output. The complete JSON target is
 *       created with {@code CREATE_NEW} and forced before a handle-relative {@code CREATE_NEW}
 *       commit marker is written. Restore accepts a target only when its marker is present and
 *       its SHA-256 digest matches; this is an application-level logical commit protocol, not an
 *       operating-system atomic rename.</li>
 *   <li>Labels and backup ids are strict allowlisted tokens; path traversal, absolute paths,
 *       symlink escapes and overwrites of existing snapshots are rejected.</li>
 *   <li>Restore runs a full preflight (parse/schema/records/currency) before touching live
 *       state, then re-checks the no-online-player gate under the operation lock, then writes
 *       a safety backup of the current live state; only after all gates pass is
 *       {@code lifecycle.restore} invoked. On success the leaderboard cache is invalidated and
 *       the caller must restart the server before players return — this service performs no
 *       session hot-refresh.</li>
 *   <li>A single operation lock serializes backup/restore; concurrent callers get a typed
 *       busy failure instead of blocking, and the lock is released on every outcome.</li>
 * </ul>
 */
public final class BackupRestoreService {

    /** Safe label token: short, no separators, no traversal, no control characters. */
    private static final Pattern SAFE_LABEL = Pattern.compile("[A-Za-z0-9._-]{1,64}");
    /** Safe backup id token as generated by this service (file base name, no extension). */
    private static final Pattern SAFE_ID = Pattern.compile("[A-Za-z0-9._-]{1,128}");
    private static final DateTimeFormatter ID_TIMESTAMP =
            DateTimeFormatter.ofPattern("yyyyMMdd'T'HHmmss").withZone(ZoneOffset.UTC);
    private static final HexFormat HEX = HexFormat.of();
    private static final Pattern READY_MARKER = Pattern.compile("sha256=[0-9a-f]{64}\\n");
    private static final int MAX_MARKER_BYTES = 80;
    /** Fixed label used for the pre-restore snapshot of the previous live state. */
    private static final String SAFETY_LABEL = "pre-restore";

    private final PersistenceLifecycle lifecycle;
    private final Path pluginDataFolder;
    private final PlayerOnlineProbe onlineProbe;
    private final Supplier<Set<String>> knownCurrencyIds;
    private final Runnable cacheReset;
    private final Clock clock;
    private final Supplier<String> uniqueSuffix;
    private final ReentrantLock operationLock = new ReentrantLock();

    public BackupRestoreService(PersistenceLifecycle lifecycle,
                                Path pluginDataFolder,
                                PlayerOnlineProbe onlineProbe,
                                Supplier<Set<String>> knownCurrencyIds,
                                Runnable cacheReset) {
        this(lifecycle, pluginDataFolder, onlineProbe, knownCurrencyIds, cacheReset,
                () -> java.time.Instant.now(),
                () -> java.util.UUID.randomUUID().toString().substring(0, 8));
    }

    /** Deterministic seam: injects the clock and the unique-id suffix source for reproducible ids. */
    BackupRestoreService(PersistenceLifecycle lifecycle,
                         Path pluginDataFolder,
                         PlayerOnlineProbe onlineProbe,
                         Supplier<Set<String>> knownCurrencyIds,
                         Runnable cacheReset,
                         Clock clock,
                         Supplier<String> uniqueSuffix) {
        this.lifecycle = lifecycle;
        this.pluginDataFolder = pluginDataFolder;
        this.onlineProbe = onlineProbe;
        this.knownCurrencyIds = knownCurrencyIds;
        this.cacheReset = cacheReset;
        this.clock = clock;
        this.uniqueSuffix = uniqueSuffix;
    }

    // ---------------- backup ----------------

    /**
     * Create a logical v2 snapshot of the live state. {@code label} may be null/blank; when
     * present it must match the safe-label allowlist.
     */
    public BackupResult createBackup(String label) {
        String safeLabel;
        try {
            safeLabel = normalizeLabel(label);
        } catch (IllegalArgumentException e) {
            return BackupResult.failure(BackupRestoreError.LABEL_INVALID, e.getMessage());
        }
        if (!operationLock.tryLock()) {
            return BackupResult.failure(BackupRestoreError.BUSY,
                    "another backup or restore operation is already running");
        }
        try {
            ByteArrayOutputStream buffer = new ByteArrayOutputStream();
            lifecycle.backup(buffer);
            byte[] bytes = buffer.toByteArray();
            // Sanity gate: what we are about to persist must itself be a readable v2 model.
            SnapshotPreflight.validate(new String(bytes, StandardCharsets.UTF_8), null);
            String id = publishSnapshot(bytes, safeLabel);
            return BackupResult.success(id);
        } catch (PersistenceException e) {
            return BackupResult.failure(BackupRestoreError.IO_FAILED,
                    "backup failed: " + e.getMessage());
        } catch (IOException e) {
            return BackupResult.failure(BackupRestoreError.IO_FAILED,
                    "backup failed: " + e.getMessage());
        } finally {
            operationLock.unlock();
        }
    }

    // ---------------- restore ----------------

    /**
     * Restore the live state from the managed snapshot {@code backupId} after all safety
     * gates pass.
     */
    public RestoreResult restore(String backupId) {
        // 1. Token validation + resolve/read candidate. No live state is touched yet.
        String id;
        try {
            id = normalizeId(backupId);
        } catch (IllegalArgumentException e) {
            return RestoreResult.failure(BackupRestoreError.INVALID_REQUEST, e.getMessage());
        }
        byte[] snapshot;
        try {
            snapshot = readCandidateSnapshot(id);
        } catch (BackupMissingException e) {
            return RestoreResult.failure(BackupRestoreError.BACKUP_NOT_FOUND, e.getMessage());
        } catch (IOException e) {
            return RestoreResult.failure(BackupRestoreError.IO_FAILED,
                    "could not read backup '" + id + "': " + e.getMessage());
        }
        // 2. Preflight: parse / schema / records / currency compatibility (still read-only).
        JsonModel candidate;
        try {
            candidate = SnapshotPreflight.parse(new String(snapshot, StandardCharsets.UTF_8));
            SnapshotPreflight.checkSchemaVersion(candidate);
            SnapshotPreflight.validateRecords(candidate);
            SnapshotPreflight.checkCurrencies(candidate, knownCurrencyIds.get());
        } catch (PersistenceException e) {
            return classifyPreflightFailure(e);
        }
        // 3. Operation lock serializes against concurrent backups/restores.
        if (!operationLock.tryLock()) {
            return RestoreResult.failure(BackupRestoreError.BUSY,
                    "another backup or restore operation is already running");
        }
        try {
            // 4. Hard online-player gate, re-checked inside the lock before any write.
            if (onlineProbe.hasOnlinePlayers()) {
                return RestoreResult.failure(BackupRestoreError.PLAYERS_ONLINE,
                        "players are still online; ask everyone to leave before restoring");
            }
            // 5+6. Exclusive boundary on the SAME backend instance: ordinary repository
            // writes cannot interleave between the safety snapshot and the restore. The
            // backend lock/monitor is reentrant, so the safety backup inside may safely
            // re-enter lifecycle.backup, and it is never rejected by the service busy gate
            // because this thread already holds the service operation lock.
            try {
                return lifecycle.runExclusive(() -> {
                    BackupResult safety = createBackup(SAFETY_LABEL);
                    if (!safety.isSuccess()) {
                        return RestoreResult.failure(BackupRestoreError.SAFETY_BACKUP_FAILED,
                                "pre-restore safety snapshot failed; live state untouched — "
                                        + safety.message());
                    }
                    try {
                        lifecycle.restore(new ByteArrayInputStream(snapshot));
                    } catch (PersistenceException | IOException e) {
                        // Truthful contract: once lifecycle.restore has been entered, a
                        // backend failure does NOT prove the live state is unchanged —
                        // a failed SQL rollback or a post-commit autoCommit failure can
                        // leave it changed or committed. Never claim a rollback here.
                        return RestoreResult.failure(BackupRestoreError.RESTORE_FAILED,
                                "backend restore failed; live state was not confirmed "
                                        + "unchanged — inspect the safety backup and SQL "
                                        + "connection before any retry: " + e.getMessage());
                    }
                    // 7. Success: stale cached rankings must never survive a replaced world.
                    cacheReset.run();
                    return RestoreResult.success(id, safety.backupId());
                });
            } catch (PersistenceException | IOException e) {
                return RestoreResult.failure(BackupRestoreError.IO_FAILED,
                        "exclusive restore window failed: " + e.getMessage());
            }
        } finally {
            operationLock.unlock();
        }
    }

    // ---------------- internals: tokens ----------------

    private static String normalizeLabel(String raw) {
        if (raw == null || raw.isBlank()) {
            return null;
        }
        String label = raw.trim();
        if (!SAFE_LABEL.matcher(label).matches() || ".".equals(label) || "..".equals(label)) {
            throw new IllegalArgumentException(
                    "label may only contain letters, digits, '.', '_' and '-' (max 64 chars), "
                            + "and must not be '.' or '..': " + truncate(raw));
        }
        return label;
    }

    private static String normalizeId(String raw) {
        if (raw == null || raw.isBlank()) {
            throw new IllegalArgumentException("backup id is required");
        }
        String id = raw.trim();
        if (!SAFE_ID.matcher(id).matches() || ".".equals(id) || "..".equals(id)) {
            throw new IllegalArgumentException(
                    "backup id may only contain letters, digits, '.', '_' and '-', "
                            + "must not be '.' or '..', and must not contain path separators: "
                            + truncate(raw));
        }
        return id;
    }

    private static String truncate(String s) {
        String trimmed = s.replaceAll("[\\p{Cntrl}]", "?");
        return trimmed.length() <= 64 ? trimmed : trimmed.substring(0, 61) + "...";
    }

    private static RestoreResult classifyPreflightFailure(PersistenceException e) {
        String message = e.getMessage() == null ? "" : e.getMessage().toLowerCase(Locale.ROOT);
        if (message.contains("schema version")) {
            return RestoreResult.failure(BackupRestoreError.SCHEMA_INCOMPATIBLE, e.getMessage());
        }
        if (message.contains("currencies unknown")) {
            return RestoreResult.failure(BackupRestoreError.CURRENCY_INCOMPATIBLE, e.getMessage());
        }
        return RestoreResult.failure(BackupRestoreError.SNAPSHOT_INVALID, e.getMessage());
    }

    // ---------------- internals: controlled paths ----------------

    /** Validated controlled directory plus the filesystem identity captured at validation. */
    private record ControlledDirectory(Path realDir, Object identity) {
    }

    /**
     * Resolve (and create) the controlled backups directory, proving via real paths that it
     * stays inside the plugin data folder even when either side is reached through symlinks,
     * and capturing the directory's filesystem identity ({@code fileKey}) at validation time
     * so {@link #openSecureHandle} can prove the OPENED directory is still the same one.
     *
     * <p>An existing {@code backups} entry is inspected with {@link LinkOption#NOFOLLOW_LINKS}
     * BEFORE any creation attempt: a symbolic link there is rejected outright instead of being
     * followed or created through. Creation only happens when the entry is absent, and the
     * result is re-checked afterwards, so the containment proof below never depends on
     * platform-specific {@code mkdir} symlink semantics.</p>
     */
    private ControlledDirectory controlledDirectory(boolean create) throws IOException {
        Path dataRoot = pluginDataFolder.toAbsolutePath().normalize();
        Path dir = dataRoot.resolve("backups");
        if (Files.exists(dir, LinkOption.NOFOLLOW_LINKS)) {
            // Never follow an existing entry: a symlinked backups path (dangling or pointing
            // outside) is rejected before anything is created or resolved through it.
            if (Files.isSymbolicLink(dir)) {
                throw new IOException("backup directory must not be a symbolic link: " + dir);
            }
            if (!Files.isDirectory(dir, LinkOption.NOFOLLOW_LINKS)) {
                throw new IOException("backup path exists but is not a directory: " + dir);
            }
        } else if (create) {
            Files.createDirectories(dir);
            // Re-check after creation: a concurrently planted link must not survive into
            // the real-path resolution below.
            if (Files.isSymbolicLink(dir)) {
                throw new IOException("backup directory was replaced by a symbolic link: " + dir);
            }
        } else {
            throw new IOException("backup directory does not exist");
        }
        Path realRoot = dataRoot.toRealPath();
        Path realDir = dir.toRealPath();
        if (!realDir.startsWith(realRoot)) {
            throw new IOException("backup directory resolves outside the plugin data folder: "
                    + realDir);
        }
        Object identity = Files.readAttributes(realDir, BasicFileAttributes.class,
                LinkOption.NOFOLLOW_LINKS).fileKey();
        if (identity == null) {
            // Providers may legally return a null fileKey; without an identity this
            // directory can never be proven to be the validated one. Fail closed here
            // rather than comparing against an unknown later.
            throw new IOException("filesystem does not provide an identity for the backup "
                    + "directory; refusing unguarded access");
        }
        return new ControlledDirectory(realDir, identity);
    }

    private byte[] readCandidateSnapshot(String id) throws IOException {
        ControlledDirectory controlled;
        try {
            controlled = controlledDirectory(false);
        } catch (IOException e) {
            throw new BackupMissingException("no such backup: " + id);
        }
        try (SecureDirectoryStream<Path> secure =
                     openSecureHandle(controlled.realDir(), controlled.identity())) {
            Path targetName = relativeName(controlled, id + ".json");
            Path markerName = relativeName(controlled, id + ".ready");
            try {
                // The marker is the logical commit point. Both marker and target are opened
                // relative to the already verified directory handle and never through the
                // mutable parent path.
                String expectedDigest = readReadyMarker(secure, markerName);
                byte[] snapshot = readHandleFile(secure, targetName, Integer.MAX_VALUE);
                String actualDigest = HEX.formatHex(sha256(snapshot));
                if (!MessageDigest.isEqual(expectedDigest.getBytes(StandardCharsets.US_ASCII),
                        actualDigest.getBytes(StandardCharsets.US_ASCII))) {
                    throw new IOException("backup commit marker does not match snapshot content");
                }
                return snapshot;
            } catch (IOException e) {
                throw new BackupMissingException(
                        "no committed backup (missing, incomplete, or unsafe target): " + id);
            }
        }
    }

    private static Path relativeName(ControlledDirectory controlled, String name) {
        return controlled.realDir().getFileSystem().getPath(name);
    }

    private static String readReadyMarker(SecureDirectoryStream<Path> secure, Path markerName)
            throws IOException {
        byte[] markerBytes = readHandleFile(secure, markerName, MAX_MARKER_BYTES);
        String marker = new String(markerBytes, StandardCharsets.US_ASCII);
        if (!READY_MARKER.matcher(marker).matches()) {
            throw new IOException("backup commit marker is malformed");
        }
        return marker.substring("sha256=".length(), marker.length() - 1);
    }

    private static byte[] readHandleFile(SecureDirectoryStream<Path> secure, Path relative,
                                         int maxBytes) throws IOException {
        BasicFileAttributeView view = secure.getFileAttributeView(relative,
                BasicFileAttributeView.class, LinkOption.NOFOLLOW_LINKS);
        if (view == null) {
            throw new IOException("filesystem does not provide no-follow attributes for a "
                    + "secure backup entry");
        }
        BasicFileAttributes attributes = view.readAttributes();
        if (!attributes.isRegularFile()) {
            throw new IOException("backup entry is not a regular file");
        }
        long size = attributes.size();
        if (size > maxBytes || size > Integer.MAX_VALUE) {
            throw new IOException("backup entry is too large");
        }
        ByteBuffer buffer = ByteBuffer.allocate((int) size);
        try (var channel = secure.newByteChannel(relative,
                Set.of(StandardOpenOption.READ, LinkOption.NOFOLLOW_LINKS))) {
            while (buffer.hasRemaining()) {
                if (channel.read(buffer) < 0) {
                    throw new IOException("backup entry was truncated while reading");
                }
            }
        }
        return buffer.array();
    }

    private static byte[] sha256(byte[] bytes) throws IOException {
        try {
            return MessageDigest.getInstance("SHA-256").digest(bytes);
        } catch (NoSuchAlgorithmException e) {
            throw new IOException("SHA-256 is unavailable; refusing unverified backup", e);
        }
    }

    /**
     * Opens the controlled directory as a {@link SecureDirectoryStream} and proves the
     * OPENED directory still carries the filesystem identity captured at validation time
     * before any read/write is handed to the handle. A swap of the last directory entry
     * between validation and open (for example to an external symlink) therefore fails
     * closed here instead of leaking an unexpected directory into snapshot I/O. Providers
     * without secure directory handles — or without per-handle identity attributes — fail
     * closed too: there is deliberately no unguarded path fallback.
     */
    SecureDirectoryStream<Path> openSecureHandle(Path dir, Object expectedIdentity)
            throws IOException {
        DirectoryStream<Path> stream = Files.newDirectoryStream(dir);
        if (!(stream instanceof SecureDirectoryStream<Path> secure)) {
            stream.close();
            throw new IOException("filesystem does not support secure directory handles; "
                    + "refusing unguarded access to the backup directory");
        }
        Object openedIdentity;
        try {
            BasicFileAttributeView handleView = secure.getFileAttributeView(
                    dir.getFileSystem().getPath("."), BasicFileAttributeView.class);
            // "." resolved against the open directory handle refers to the opened
            // directory itself (openat semantics), so its fileKey is the handle's identity.
            // A provider may return a null view or a null fileKey; both mean the identity
            // of this handle cannot be proven and must fail closed.
            if (handleView == null) {
                throw new IOException("filesystem does not provide attributes for secure "
                        + "handle entries");
            }
            openedIdentity = handleView.readAttributes().fileKey();
        } catch (IOException | RuntimeException e) {
            secure.close();
            throw new IOException("cannot verify the identity of the opened backup "
                    + "directory; refusing unguarded access", e);
        }
        if (openedIdentity == null || expectedIdentity == null
                || !openedIdentity.equals(expectedIdentity)) {
            secure.close();
            throw new IOException("backup directory changed while opening a secure handle; "
                    + "refusing to operate on the unexpected directory");
        }
        return secure;
    }

    /** Marks a restore target that must be reported as not found rather than an I/O error. */
    private static final class BackupMissingException extends IOException {
        private BackupMissingException(String message) {
            super(message);
        }
    }

    /**
     * Write the snapshot bytes under a fresh unique id using an application-level commit
     * protocol. The JSON target is created directly with handle-relative {@code CREATE_NEW},
     * written completely, and forced. Only then is the handle-relative {@code .ready} marker
     * created with {@code CREATE_NEW}; the marker contains the target SHA-256 digest and is the
     * logical commit point observed by restore.
     *
     * <p>Provider requirement: all snapshot and marker I/O needs secure directory handles,
     * no-follow attributes, regular-file checks, and forced file channels. Any missing
     * capability fails closed; there is deliberately no path-based move, hard-link, copy, or
     * overwrite fallback. A failure after target creation may leave an uncommitted orphan with
     * no marker; restore will reject it.</p>
     *
     * @return the generated backup id (file base name without extension)
     */
    private String publishSnapshot(byte[] bytes, String label) throws IOException {
        ControlledDirectory controlled = controlledDirectory(true);
        Path dir = controlled.realDir();
        String id = buildId(label);
        Path targetName = dir.getFileSystem().getPath(id + ".json");
        Path markerName = dir.getFileSystem().getPath(id + ".ready");
        byte[] markerBytes = ("sha256=" + HEX.formatHex(sha256(bytes)) + "\n")
                .getBytes(StandardCharsets.US_ASCII);
        try (SecureDirectoryStream<Path> secure =
                     openSecureHandle(dir, controlled.identity())) {
            assertAbsent(secure, targetName, id + ".json");
            assertAbsent(secure, markerName, id + ".ready");
            try (FileChannel channel = (FileChannel) secure.newByteChannel(targetName,
                    EnumSet.of(StandardOpenOption.WRITE, StandardOpenOption.CREATE_NEW))) {
                writeFully(channel, bytes);
                channel.force(true);
            }
            // The marker is deliberately created only after the complete target is forced.
            // CREATE_NEW makes both the target and commit marker no-replace operations even
            // when another process wins the name race after the absence checks.
            try (FileChannel channel = (FileChannel) secure.newByteChannel(markerName,
                    EnumSet.of(StandardOpenOption.WRITE, StandardOpenOption.CREATE_NEW))) {
                writeFully(channel, markerBytes);
                channel.force(true);
            }
        } catch (FileAlreadyExistsException e) {
            throw new IOException("backup id collision; refusing to overwrite " + id, e);
        }
        return id;
    }

    private static void assertAbsent(SecureDirectoryStream<Path> secure, Path relative,
                                     String displayName) throws IOException {
        BasicFileAttributeView view = secure.getFileAttributeView(relative,
                BasicFileAttributeView.class, LinkOption.NOFOLLOW_LINKS);
        if (view == null) {
            throw new IOException("filesystem does not provide no-follow attributes for secure "
                    + "backup entries; refusing unguarded write");
        }
        try {
            view.readAttributes();
            throw new IOException("backup entry already exists; refusing to overwrite "
                    + displayName);
        } catch (NoSuchFileException absent) {
            // The CREATE_NEW operation below remains authoritative against a race.
        }
    }

    private static void writeFully(FileChannel channel, byte[] bytes) throws IOException {
        ByteBuffer buffer = ByteBuffer.wrap(bytes);
        while (buffer.hasRemaining()) {
            int written = channel.write(buffer);
            if (written <= 0) {
                throw new IOException("secure backup write made no progress");
            }
        }
    }

    private String buildId(String label) {
        StringBuilder id = new StringBuilder()
                .append(ID_TIMESTAMP.format(clock.instant()))
                .append('-').append(uniqueSuffix.get());
        if (label != null) {
            id.append('-').append(label);
        }
        String result = id.toString();
        if (!SAFE_ID.matcher(result).matches() || ".".equals(result) || "..".equals(result)) {
            throw new IllegalStateException("generated backup id failed its own safety check");
        }
        return result;
    }
}
