name: ${name}
version: ${version}
description: ${description}
main: com.smile.aceeconomy.AceEconomy
author: Smile
api-version: ${apiVersion}
folia-supported: true
depend:
  - Vault
softdepend:
  - PlaceholderAPI

commands:
  money:
    description: 查看自己的餘額
    usage: /<command>
    aliases: [balance, bal]
  pay:
    description: 轉帳給其他玩家
    usage: /<command> <玩家> <金額>
  aceeco:
    description: AceEconomy 管理指令
    usage: /<command> <give|take|set> <玩家> <金額>
  withdraw:
    description: 提領銀行支票
    usage: /<command> <金額>
  baltop:
    description: 查看富豪排行榜
    usage: /<command> [頁碼]
    aliases: [balancetop, top]

permissions:
  aceeconomy.use:
    description: 允許使用基本經濟指令
    default: true
  aceeconomy.pay:
    description: 允許使用轉帳指令
    default: true
  aceeconomy.withdraw:
    description: 允許使用提領支票指令
    default: true
  aceeconomy.command.baltop:
    description: 允許使用排行榜指令
    default: true
  aceeconomy.admin:
    description: 允許使用管理指令
    default: op
