name: ${name}
version: ${version}
description: ${description}
main: com.smile.aceeconomy.AceEconomy
author: Smile
api-version: ${apiVersion}
folia-supported: true
depend:
  - Vault
softdepend:
  - PlaceholderAPI

commands:
  money:
    description: 查看自己的餘額
    usage: /<command>
    aliases: [balance, bal]
  pay:
    description: 轉帳給其他玩家
    usage: /<command> <玩家> <金額>
  aceeco:
    description: AceEconomy 管理指令
    usage: /<command> <give|take|set> <玩家> <金額>
  withdraw:
    description: 提領銀行支票
    usage: /<command> <金額>
  baltop:
    description: 查看富豪排行榜
    usage: /<command> [頁碼]
    aliases: [balancetop, top]
  bank:
    description: Open the AceEconomy Dashboard.
    aliases: [menu, bankmenu]
    usage: /bank

permissions:
  aceeconomy.admin:
    description: AceEconomy Admin (Wildcard)
    default: op
    children:
      aceeconomy.command.pay: true
      aceeconomy.command.money: true
      aceeconomy.command.baltop: true
      aceeconomy.command.withdraw: true
      aceeconomy.admin.give: true
      aceeconomy.admin.take: true
      aceeconomy.admin.set: true
      aceeconomy.admin.reload: true
      aceeconomy.admin.history: true
      aceeconomy.admin.rollback: true
      aceeconomy.bypass.debt: true
      aceeconomy.command.bank: true
  aceeconomy.command.pay:
    description: Allow use of /pay
    default: true
  aceeconomy.command.money:
    description: Allow use of /money
    default: true
  aceeconomy.command.baltop:
    description: Allow use of /baltop
    default: true
  aceeconomy.command.withdraw:
    description: Allow use of /withdraw
    default: true
  aceeconomy.admin.give:
    description: Allow use of /aceeco give
    default: op
  aceeconomy.admin.take:
    description: Allow use of /aceeco take
    default: op
  aceeconomy.admin.set:
    description: Allow use of /aceeco set
    default: op
  aceeconomy.admin.reload:
    description: Allow use of /aceeco reload
    default: op
  aceeconomy.admin.history:
    description: Allow use of /aceeco history
    default: op
  aceeconomy.admin.rollback:
    description: Allow use of /aceeco rollback
    default: op
  aceeconomy.bypass.debt:
    description: Allow player to bypass debt limits
    default: op
  aceeconomy.command.bank:
    description: Allows opening the bank menu.
    default: true
